### ISSUE TITLE
How use flatPackage in pom.xml?

### ISSUE THREAD

**Issue by thinkerou** [thesamet/scalapb-maven-example#4]
In `build.sbt`, I can write the follow code:

```scala
  PB.targets in Compile := Seq(
    scalapb.gen(flatPackage = true) -> (sourceManaged in Compile).value
  )
```

I want to write the code in `pom.xml`, how should I do? thanks!

**Comment by thesamet** [comment]
Hi @thinkerou , see "passing generator parameters" in https://scalapb.github.io/scalapbc.html
